# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### gauti visus postus is DB

GET http://localhost:8080/api/posts
Content-Type: application/json

### login

POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=Jonas&password=labas

### gauti visus prisiloginusio userio postus

GET http://localhost:8080/api/user/posts
Content-Type: application/json
Cookie: JSESSIONID=FF26F46DBE11F028060190C01CE66CBA

### sukurti posta (gali tik prisilogines user ir kaip autorius jis bus pridetas serveryje patikrinus jo principal name)

POST http://localhost:8080/api/post
Content-Type: application/json
Cookie: JSESSIONID=8AA6035C3509B2FF7391A36C9F1C963E

{"title": "testas", "article": "testas"}


### delete post (gali tik prisilogines user ir pries delete bus patikrinta ar jis yra posto autorius)

DELETE http://localhost:8080/api/post/3
Content-Type: application/json
Cookie: JSESSIONID=E6F32F4E85B0618248D4E28FCE274022

###